### ISSUE TITLE
Get CI hooked up.

### ISSUE THREAD

**Issue by Ross-Hunter** [chiperific/filterbuildscheduler#192]
Ok, but for real this time. I don't think I'm an all-the-way admin so I can't hook up circle ci.

**Comment by chiperific** [comment]
circleci is attached, but the config.yml file is giving me fits, so its failing on its own setup.

**Comment by chiperific** [comment]
See .circleci/config.yml line#75

Produces this error: `LoadError: cannot load such file -- rspec_junit_formatter`

**Comment by chiperific** [comment]
CircleCI is performing as expected.
